### ISSUE TITLE
Windows installer default install path

### ISSUE THREAD

**Issue by markusschloesser** [RitaAndAurora/kijimi-babu-frik#3]
on my x64 system, the installer suggested the wrong default install path "C:\Program Files (x86)" even though the Program itself is 64 bit, so should've been "C:\Program Files"

**Comment by ffont** [comment]
Thanks for reporting! the installer takes as default path a files" directory path which (I thought) is based on some system configuration. However, I think I can force it to use the 64 bit program files path by default. I'll include that in the next release.

**Comment by ffont** [comment]
Closing this issue as should have been fixed in 1.0.1 release
