### ISSUE TITLE
Question about sysex communication with Kijimi

### ISSUE THREAD

**Issue by christofmuc** [RitaAndAurora/kijimi-babu-frik#5]
Hello, this is not an issue but just a friendly question! I understand this is a working editor for the Kijimi but also works as a Librarian - did you get the information from Black Corporation on the sysex requests required to dump patches? I am asking because I haven't heard back from them, and want to add the Kijimi to my project, a generic Sysex Librarian for all synthesizers, which is user extensible for new devices.

Also, I could look into your code to spot the required information, but thought it'd be more polite just asking if you mind sharing information? 

My project btw is at https://github.com/christofmuc/KnobKraft-orm

Love your UI and your design!

**Comment by ffont** [comment]
Hi @christofmuc, thanks for your kind words and your comment. After I insisted a number of times I finally got Black Corporation helping with "my" project and they did help immensely. I'll talk to them to see what information I can share with you. I don't think there'll be any problem. I guess what you need exactly is to know what sysex messsages you should use to send/receive patches from KIJIMI, but you don't need to know what each byte of the patch files "means" right?

Nice project!!

**Comment by christofmuc** [comment]
@ffont Thank you! Yes, the single patch/bank request and replies, plus a device detection (device inquiry) if available is sufficient to use the Librarian. There are advanced features enabled when the parameters can be unpacked (i.e. Patch Diff on a parameter by parameter basis), but that is optional, as the information is not availabel for all devices.

**Comment by ffont** [comment]
I got response from BC, emailing you.
