### ISSUE TITLE
Windows version doesn't open at all

### ISSUE THREAD

**Issue by markusschloesser** [RitaAndAurora/kijimi-babu-frik#7]
hey,
unfortunately in addition to the previous issues, unfortunately babu frik will not open at all on Win10 22H1 and will just crash.

From the event log:
Faulting application name: BabuFrik.exe, version: 1.0.1.0, time stamp: 0x5fc4dceb
Faulting module name: BabuFrik.exe, version: 1.0.1.0, time stamp: 0x5fc4dceb
Exception code: 0xc0000005
Fault offset: 0x000000000030c6ff
Faulting process id: 0x3c18
Faulting application start time: 0x01d87e0086642342
Faulting application path: C:\Program Files (x86)\BabuFrik\BabuFrik\BabuFrik.exe
Faulting module path: C:\Program Files (x86)\BabuFrik\BabuFrik\BabuFrik.exe
Report Id: 0000032c-e345-42c5-ad81-f9b58bff9921
Faulting package full name: 
Faulting package-relative application ID: `

and

Fault bucket 2202125777417427010, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0
Problem signature:
P1: BabuFrik.exe
P2: 1.0.1.0
P3: 5fc4dceb
P4: BabuFrik.exe
P5: 1.0.1.0
P6: 5fc4dceb
P7: c0000005
P8: 000000000030c6ff
P9: 
P10:

**Comment by ffont** [comment]
Was this after updating Babu Frik to a new version?
It could be that there is some saved file which is incompatible with newer version and it should be deleted or something like that. You should be able to find some file named BabuFrik.settings in a path similar to "c://Program Files/Babu Frik/" (not sure because I don't have windows computer now to try). You could try to remove that file and open Babu again.

**Comment by markusschloesser** [comment]
Did I miss something? I only see 1.01 on the release page, is there a newer one?
There's nothing besides the program files in that directory. I will search in other paths again. Thanks for the response! 😊

**Comment by ffont** [comment]
1.0.1 is the latest indeed. I guess you also tried re-install?
Can you try running in another computer as well?
Unfortunately this is hard to debug for me as I don't use Windows and don't have a lot of experience with that. I might be able to share a debug version of Babu Frik and see if it generates error reports which are more useful. Let me know if you can find/delete the settings file and this still does not help.

**Comment by markusschloesser** [comment]
1. re-installation on main music pc didn't help, still crashing (in fact, not even opening, I only see the crash data in the event viewer)
2. it DOES work on my laptop, though! :-)
3. uninstalling BF on the main pc and then installing freshly: still crashes

Do you know where the installer puts other things, so that I can clean up manually?
I would also gladly take the debug version! Then at least we know whats happening :-)

**Comment by markusschloesser** [comment]
ah, trashing the settings file in C:\Users\USERNAME\AppData\Roaming\Babu Frik\
solved it, it runs now. Thanks!
Maybe something for an FAQ entry?

**Comment by ffont** [comment]
Thanks for finding the solution and reporting :)
